"""initial migration

Revision ID: 285f077cd2ef
Revises: 
Create Date: 2026-08-05 22:27:53.121883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '285f077cd2ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('status', sa.String(), nullable=False))
    op.add_column('assignments', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'assignments', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_column('assignments', 'course_id')
    op.drop_column('assignments', 'status')
    # ### end Alembic commands ###
