"""allow flashcards from documents

Revision ID: 56c9326b963e
Revises: d9fab0cd0230
Create Date: 2026-08-06 16:14:37.873754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c9326b963e'
down_revision: Union[str, Sequence[str], None] = 'd9fab0cd0230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcards', sa.Column('document_id', sa.Integer(), nullable=True))
    op.alter_column('flashcards', 'note_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'flashcards', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flashcards', type_='foreignkey')
    op.alter_column('flashcards', 'note_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('flashcards', 'document_id')
    # ### end Alembic commands ###
